import {Gun} from "./gun";

export const GUNS: Gun[] = [
    {
        "id": 1,
        "name": "Colt Revolver",
        "type": "HG",
        "damage": 36,
        "dodge": 76,
        "hit": 49,
        "attackSpeed": 47,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Fire Command"
    },
    {
        "id": 2,
        "name": "M1911",
        "type": "HG",
        "damage": 27,
        "dodge": 74,
        "hit": 50,
        "attackSpeed": 57,
        "hp": 73,
        "reloadTime": null,
        "armor": null,
        "skill": "Smoke Grenade"
    },
    {
        "id": 3,
        "name": "M9",
        "type": "HG",
        "damage": 29,
        "dodge": 66,
        "hit": 56,
        "attackSpeed": 61,
        "hp": 76,
        "reloadTime": null,
        "armor": null,
        "skill": "Flashbang"
    },
    {
        "id": 5,
        "name": "Nagant Revolver",
        "type": "HG",
        "damage": 32,
        "dodge": 92,
        "hit": 46,
        "attackSpeed": 44,
        "hp": 70,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Supression N"
    },
    {
        "id": 6,
        "name": "Tokarev",
        "type": "HG",
        "damage": 31,
        "dodge": 66,
        "hit": 47,
        "attackSpeed": 52,
        "hp": 86,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Command"
    },
    {
        "id": 7,
        "name": "Stechkin",
        "type": "HG",
        "damage": 28,
        "dodge": 66,
        "hit": 44,
        "attackSpeed": 64,
        "hp": 83,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Command T"
    },
    {
        "id": 8,
        "name": "Makarov",
        "type": "HG",
        "damage": 26,
        "dodge": 96,
        "hit": 61,
        "attackSpeed": 61,
        "hp": 63,
        "reloadTime": null,
        "armor": null,
        "skill": "Precision Suppression"
    },
    {
        "id": 9,
        "name": "P38",
        "type": "HG",
        "damage": 28,
        "dodge": 81,
        "hit": 49,
        "attackSpeed": 57,
        "hp": 66,
        "reloadTime": null,
        "armor": null,
        "skill": "Flare"
    },
    {
        "id": 10,
        "name": "PPK",
        "type": "HG",
        "damage": 25,
        "dodge": 100,
        "hit": 59,
        "attackSpeed": 63,
        "hp": 57,
        "reloadTime": null,
        "armor": null,
        "skill": "Annihilation Command"
    },
    {
        "id": 11,
        "name": "P08",
        "type": "HG",
        "damage": 31,
        "dodge": 80,
        "hit": 46,
        "attackSpeed": 55,
        "hp": 70,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Command N"
    },
    {
        "id": 12,
        "name": "C96",
        "type": "HG",
        "damage": 29,
        "dodge": 61,
        "hit": 41,
        "attackSpeed": 62,
        "hp": 83,
        "reloadTime": null,
        "armor": null,
        "skill": "Flare"
    },
    {
        "id": 13,
        "name": "Type 92",
        "type": "HG",
        "damage": 31,
        "dodge": 80,
        "hit": 46,
        "attackSpeed": 61,
        "hp": 63,
        "reloadTime": null,
        "armor": null,
        "skill": "Charge Command"
    },
    {
        "id": 14,
        "name": "Astra Revolver",
        "type": "HG",
        "damage": 33,
        "dodge": 88,
        "hit": 45,
        "attackSpeed": 52,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Command"
    },
    {
        "id": 15,
        "name": "Glock 17",
        "type": "HG",
        "damage": 29,
        "dodge": 87,
        "hit": 58,
        "attackSpeed": 61,
        "hp": 63,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Supression"
    },
    {
        "id": 16,
        "name": "Thompson",
        "type": "SMG",
        "damage": 31,
        "dodge": 54,
        "hit": 12,
        "attackSpeed": 81,
        "hp": 238,
        "reloadTime": null,
        "armor": null,
        "skill": "Force Shield"
    },
    {
        "id": 17,
        "name": "M3",
        "type": "SMG",
        "damage": 30,
        "dodge": 67,
        "hit": 13,
        "attackSpeed": 68,
        "hp": 185,
        "reloadTime": null,
        "armor": null,
        "skill": "Hand Grenade"
    },
    {
        "id": 18,
        "name": "MAC-10",
        "type": "SMG",
        "damage": 28,
        "dodge": 68,
        "hit": 11,
        "attackSpeed": 91,
        "hp": 176,
        "reloadTime": null,
        "armor": null,
        "skill": "Smoke Grenade"
    },
    {
        "id": 19,
        "name": "FMG-9",
        "type": "SMG",
        "damage": 26,
        "dodge": 90,
        "hit": 13,
        "attackSpeed": 92,
        "hp": 141,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Focus"
    },
    {
        "id": 20,
        "name": "Vector",
        "type": "SMG",
        "damage": 30,
        "dodge": 71,
        "hit": 11,
        "attackSpeed": 101,
        "hp": 185,
        "reloadTime": null,
        "armor": null,
        "skill": "Incendiary Grenade"
    },
    {
        "id": 21,
        "name": "PPSh-41",
        "type": "SMG",
        "damage": 26,
        "dodge": 56,
        "hit": 11,
        "attackSpeed": 93,
        "hp": 194,
        "reloadTime": null,
        "armor": null,
        "skill": "Hand Grenade"
    },
    {
        "id": 22,
        "name": "PPS-43",
        "type": "SMG",
        "damage": 33,
        "dodge": 65,
        "hit": 13,
        "attackSpeed": 74,
        "hp": 176,
        "reloadTime": null,
        "armor": null,
        "skill": "Hand Grenade"
    },
    {
        "id": 23,
        "name": "PP-90",
        "type": "SMG",
        "damage": 25,
        "dodge": 86,
        "hit": 13,
        "attackSpeed": 96,
        "hp": 159,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Focus T"
    },
    {
        "id": 24,
        "name": "PP-2000",
        "type": "SMG",
        "damage": 29,
        "dodge": 74,
        "hit": 11,
        "attackSpeed": 80,
        "hp": 159,
        "reloadTime": null,
        "armor": null,
        "skill": "Hand Grenade"
    },
    {
        "id": 25,
        "name": "MP40",
        "type": "SMG",
        "damage": 29,
        "dodge": 58,
        "hit": 13,
        "attackSpeed": 76,
        "hp": 185,
        "reloadTime": null,
        "armor": null,
        "skill": "Incendiary Grenade"
    },
    {
        "id": 26,
        "name": "MP5",
        "type": "SMG",
        "damage": 30,
        "dodge": 68,
        "hit": 13,
        "attackSpeed": 89,
        "hp": 168,
        "reloadTime": null,
        "armor": null,
        "skill": "Force Shield"
    },
    {
        "id": 27,
        "name": "Skorpion",
        "type": "SMG",
        "damage": 24,
        "dodge": 83,
        "hit": 13,
        "attackSpeed": 95,
        "hp": 159,
        "reloadTime": null,
        "armor": null,
        "skill": "Incendiary Grenade"
    },
    {
        "id": 29,
        "name": "Sten MkII",
        "type": "SMG",
        "damage": 26,
        "dodge": 75,
        "hit": 15,
        "attackSpeed": 78,
        "hp": 185,
        "reloadTime": null,
        "armor": null,
        "skill": "Hand Grenade"
    },
    {
        "id": 31,
        "name": "Beretta Model 38",
        "type": "SMG",
        "damage": 33,
        "dodge": 52,
        "hit": 12,
        "attackSpeed": 75,
        "hp": 203,
        "reloadTime": null,
        "armor": null,
        "skill": "Flashbang"
    },
    {
        "id": 32,
        "name": "Micro Uzi",
        "type": "SMG",
        "damage": 29,
        "dodge": 79,
        "hit": 11,
        "attackSpeed": 104,
        "hp": 159,
        "reloadTime": null,
        "armor": null,
        "skill": "Incendiary Grenade"
    },
    {
        "id": 33,
        "name": "m45",
        "type": "SMG",
        "damage": 30,
        "dodge": 62,
        "hit": 12,
        "attackSpeed": 74,
        "hp": 185,
        "reloadTime": null,
        "armor": null,
        "skill": "Smoke Grenade"
    },
    {
        "id": 34,
        "name": "M1 Garand",
        "type": "RF",
        "damage": 120,
        "dodge": 28,
        "hit": 62,
        "attackSpeed": 37,
        "hp": 88,
        "reloadTime": null,
        "armor": null,
        "skill": "Locked Shot"
    },
    {
        "id": 35,
        "name": "M1A1",
        "type": "RF",
        "damage": 95,
        "dodge": 42,
        "hit": 67,
        "attackSpeed": 38,
        "hp": 84,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus T"
    },
    {
        "id": 36,
        "name": "Springfield",
        "type": "RF",
        "damage": 128,
        "dodge": 40,
        "hit": 72,
        "attackSpeed": 32,
        "hp": 84,
        "reloadTime": null,
        "armor": null,
        "skill": "Designated Shot"
    },
    {
        "id": 37,
        "name": "M14",
        "type": "RF",
        "damage": 108,
        "dodge": 27,
        "hit": 71,
        "attackSpeed": 43,
        "hp": 84,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 38,
        "name": "M21",
        "type": "RF",
        "damage": 118,
        "dodge": 27,
        "hit": 74,
        "attackSpeed": 35,
        "hp": 93,
        "reloadTime": null,
        "armor": null,
        "skill": "Aimed Shot"
    },
    {
        "id": 39,
        "name": "Mosin-Nagant",
        "type": "RF",
        "damage": 132,
        "dodge": 38,
        "hit": 85,
        "attackSpeed": 30,
        "hp": 88,
        "reloadTime": null,
        "armor": null,
        "skill": "Designated Shot"
    },
    {
        "id": 40,
        "name": "SVT-38",
        "type": "RF",
        "damage": 110,
        "dodge": 34,
        "hit": 59,
        "attackSpeed": 34,
        "hp": 84,
        "reloadTime": null,
        "armor": null,
        "skill": "Aimed Shot"
    },
    {
        "id": 41,
        "name": "Simonov",
        "type": "RF",
        "damage": 100,
        "dodge": 34,
        "hit": 59,
        "attackSpeed": 34,
        "hp": 93,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus"
    },
    {
        "id": 42,
        "name": "PTRD",
        "type": "RF",
        "damage": 159,
        "dodge": 29,
        "hit": 75,
        "attackSpeed": 28,
        "hp": 93,
        "reloadTime": null,
        "armor": null,
        "skill": "Interdiction Shot"
    },
    {
        "id": 43,
        "name": "SVD",
        "type": "RF",
        "damage": 130,
        "dodge": 33,
        "hit": 80,
        "attackSpeed": 37,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus"
    },
    {
        "id": 44,
        "name": "SV-98",
        "type": "RF",
        "damage": 122,
        "dodge": 28,
        "hit": 74,
        "attackSpeed": 37,
        "hp": 84,
        "reloadTime": null,
        "armor": null,
        "skill": "Interdiction Shot"
    },
    {
        "id": 46,
        "name": "Kar98k",
        "type": "RF",
        "damage": 135,
        "dodge": 41,
        "hit": 78,
        "attackSpeed": 34,
        "hp": 84,
        "reloadTime": null,
        "armor": null,
        "skill": "Chain Shot"
    },
    {
        "id": 47,
        "name": "G43",
        "type": "RF",
        "damage": 111,
        "dodge": 28,
        "hit": 58,
        "attackSpeed": 40,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus N"
    },
    {
        "id": 48,
        "name": "WA2000",
        "type": "RF",
        "damage": 130,
        "dodge": 30,
        "hit": 82,
        "attackSpeed": 39,
        "hp": 88,
        "reloadTime": null,
        "armor": null,
        "skill": "Attack Focus"
    },
    {
        "id": 49,
        "name": "Type 56",
        "type": "RF",
        "damage": 103,
        "dodge": 36,
        "hit": 65,
        "attackSpeed": 36,
        "hp": 93,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 50,
        "name": "Lee-Enfield",
        "type": "RF",
        "damage": 135,
        "dodge": 40,
        "hit": 78,
        "attackSpeed": 36,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 51,
        "name": "FN-49",
        "type": "RF",
        "damage": 111,
        "dodge": 32,
        "hit": 61,
        "attackSpeed": 32,
        "hp": 93,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 52,
        "name": "BM59",
        "type": "RF",
        "damage": 104,
        "dodge": 25,
        "hit": 52,
        "attackSpeed": 38,
        "hp": 97,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus"
    },
    {
        "id": 53,
        "name": "NTW-20",
        "type": "RF",
        "damage": 165,
        "dodge": 29,
        "hit": 75,
        "attackSpeed": 30,
        "hp": 93,
        "reloadTime": null,
        "armor": null,
        "skill": "Interdiction Shot"
    },
    {
        "id": 54,
        "name": "M16A1",
        "type": "AR",
        "damage": 48,
        "dodge": 44,
        "hit": 46,
        "attackSpeed": 75,
        "hp": 116,
        "reloadTime": null,
        "armor": null,
        "skill": "Flashbang"
    },
    {
        "id": 55,
        "name": "M4A1",
        "type": "AR",
        "damage": 46,
        "dodge": 48,
        "hit": 48,
        "attackSpeed": 79,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus T"
    },
    {
        "id": 56,
        "name": "M4 SOPMOD II",
        "type": "AR",
        "damage": 48,
        "dodge": 44,
        "hit": 49,
        "attackSpeed": 78,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": "Anti-personnel Grenade"
    },
    {
        "id": 57,
        "name": "ST AR-15",
        "type": "AR",
        "damage": 48,
        "dodge": 50,
        "hit": 50,
        "attackSpeed": 77,
        "hp": 105,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus T"
    },
    {
        "id": 58,
        "name": "AK-47",
        "type": "AR",
        "damage": 52,
        "dodge": 34,
        "hit": 35,
        "attackSpeed": 65,
        "hp": 132,
        "reloadTime": null,
        "armor": null,
        "skill": "Raid Focus"
    },
    {
        "id": 60,
        "name": "AS Val",
        "type": "AR",
        "damage": 39,
        "dodge": 49,
        "hit": 46,
        "attackSpeed": 75,
        "hp": 132,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus N"
    },
    {
        "id": 61,
        "name": "StG44",
        "type": "AR",
        "damage": 53,
        "dodge": 36,
        "hit": 46,
        "attackSpeed": 61,
        "hp": 127,
        "reloadTime": null,
        "armor": null,
        "skill": "High-explosive Grenade"
    },
    {
        "id": 62,
        "name": "G41",
        "type": "AR",
        "damage": 50,
        "dodge": 40,
        "hit": 48,
        "attackSpeed": 77,
        "hp": 127,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus T"
    },
    {
        "id": 63,
        "name": "G3",
        "type": "AR",
        "damage": 55,
        "dodge": 38,
        "hit": 46,
        "attackSpeed": 61,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": "Anti-personnel Grenade"
    },
    {
        "id": 64,
        "name": "G36",
        "type": "AR",
        "damage": 47,
        "dodge": 41,
        "hit": 44,
        "attackSpeed": 72,
        "hp": 127,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus T"
    },
    {
        "id": 65,
        "name": "HK416",
        "type": "AR",
        "damage": 51,
        "dodge": 43,
        "hit": 46,
        "attackSpeed": 76,
        "hp": 121,
        "reloadTime": null,
        "armor": null,
        "skill": "Anti-Personnel Grenade"
    },
    {
        "id": 66,
        "name": "Type 56-1",
        "type": "AR",
        "damage": 52,
        "dodge": 35,
        "hit": 35,
        "attackSpeed": 69,
        "hp": 138,
        "reloadTime": null,
        "armor": null,
        "skill": "High-explosive Grenade"
    },
    {
        "id": 68,
        "name": "L85A1",
        "type": "AR",
        "damage": 46,
        "dodge": 43,
        "hit": 43,
        "attackSpeed": 78,
        "hp": 94,
        "reloadTime": null,
        "armor": null,
        "skill": "Charge Focus"
    },
    {
        "id": 69,
        "name": "FAMAS",
        "type": "AR",
        "damage": 44,
        "dodge": 40,
        "hit": 48,
        "attackSpeed": 81,
        "hp": 121,
        "reloadTime": null,
        "armor": null,
        "skill": "High-explosive Grenade"
    },
    {
        "id": 70,
        "name": "FNC",
        "type": "AR",
        "damage": 51,
        "dodge": 37,
        "hit": 46,
        "attackSpeed": 73,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 71,
        "name": "Galil",
        "type": "AR",
        "damage": 50,
        "dodge": 43,
        "hit": 44,
        "attackSpeed": 66,
        "hp": 105,
        "reloadTime": null,
        "armor": null,
        "skill": "Precision Focus N"
    },
    {
        "id": 72,
        "name": "TAR-21",
        "type": "AR",
        "damage": 49,
        "dodge": 44,
        "hit": 48,
        "attackSpeed": 79,
        "hp": 103,
        "reloadTime": null,
        "armor": null,
        "skill": "Charge Focus"
    },
    {
        "id": 74,
        "name": "SIG-510",
        "type": "AR",
        "damage": 56,
        "dodge": 37,
        "hit": 41,
        "attackSpeed": 59,
        "hp": 116,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 75,
        "name": "M1918",
        "type": "MG",
        "damage": 96,
        "dodge": 33,
        "hit": 31,
        "attackSpeed": 114,
        "hp": 147,
        "reloadTime": 8,
        "armor": null,
        "skill": "Firepower Focus MG"
    },
    {
        "id": 77,
        "name": "M2HB",
        "type": "MG",
        "damage": 102,
        "dodge": 16,
        "hit": 18,
        "attackSpeed": 100,
        "hp": 215,
        "reloadTime": 10,
        "armor": null,
        "skill": "Barrage End"
    },
    {
        "id": 78,
        "name": "M60",
        "type": "MG",
        "damage": 92,
        "dodge": 26,
        "hit": 26,
        "attackSpeed": 111,
        "hp": 182,
        "reloadTime": 9,
        "armor": null,
        "skill": "Firepower Focus N-MG"
    },
    {
        "id": 79,
        "name": "M249 SAW",
        "type": "MG",
        "damage": 79,
        "dodge": 36,
        "hit": 35,
        "attackSpeed": 139,
        "hp": 157,
        "reloadTime": 8,
        "armor": null,
        "skill": "Lock and Load N-MG"
    },
    {
        "id": 80,
        "name": "M1919A4",
        "type": "MG",
        "damage": 96,
        "dodge": 22,
        "hit": 26,
        "attackSpeed": 99,
        "hp": 182,
        "reloadTime": 9,
        "armor": null,
        "skill": "Hunting Impulse"
    },
    {
        "id": 81,
        "name": "LWMMG",
        "type": "MG",
        "damage": 95,
        "dodge": 22,
        "hit": 24,
        "attackSpeed": 90,
        "hp": 174,
        "reloadTime": 9,
        "armor": null,
        "skill": "Hunting Impulse"
    },
    {
        "id": 82,
        "name": "DP28",
        "type": "MG",
        "damage": 88,
        "dodge": 31,
        "hit": 28,
        "attackSpeed": 114,
        "hp": 141,
        "reloadTime": 9,
        "armor": null,
        "skill": "Lock and Load"
    },
    {
        "id": 84,
        "name": "RPD",
        "type": "MG",
        "damage": 82,
        "dodge": 34,
        "hit": 34,
        "attackSpeed": 121,
        "hp": 165,
        "reloadTime": 8,
        "armor": null,
        "skill": "Firepower Focus MG"
    },
    {
        "id": 85,
        "name": "PK",
        "type": "MG",
        "damage": 93,
        "dodge": 22,
        "hit": 21,
        "attackSpeed": 83,
        "hp": 190,
        "reloadTime": 11,
        "armor": null,
        "skill": "Barrage End"
    },
    {
        "id": 86,
        "name": "MG42",
        "type": "MG",
        "damage": 87,
        "dodge": 26,
        "hit": 23,
        "attackSpeed": 132,
        "hp": 165,
        "reloadTime": 10,
        "armor": null,
        "skill": "Firepower Focus MG"
    },
    {
        "id": 87,
        "name": "MG34",
        "type": "MG",
        "damage": 85,
        "dodge": 25,
        "hit": 22,
        "attackSpeed": 120,
        "hp": 165,
        "reloadTime": 10,
        "armor": null,
        "skill": "Firepower Focus MG"
    },
    {
        "id": 88,
        "name": "MG3",
        "type": "MG",
        "damage": 85,
        "dodge": 21,
        "hit": 26,
        "attackSpeed": 130,
        "hp": 198,
        "reloadTime": 10,
        "armor": null,
        "skill": "Lock and Load"
    },
    {
        "id": 89,
        "name": "Bren",
        "type": "MG",
        "damage": 89,
        "dodge": 28,
        "hit": 31,
        "attackSpeed": 102,
        "hp": 174,
        "reloadTime": 8,
        "armor": null,
        "skill": "Lock and Load"
    },
    {
        "id": 90,
        "name": "FNP-9",
        "type": "HG",
        "damage": 28,
        "dodge": 83,
        "hit": 53,
        "attackSpeed": 61,
        "hp": 60,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Suppression"
    },
    {
        "id": 91,
        "name": "MP-446",
        "type": "HG",
        "damage": 30,
        "dodge": 74,
        "hit": 53,
        "attackSpeed": 59,
        "hp": 66,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Supression"
    },
    {
        "id": 92,
        "name": "Spectre M4",
        "type": "SMG",
        "damage": 25,
        "dodge": 66,
        "hit": 12,
        "attackSpeed": 88,
        "hp": 176,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Focus"
    },
    {
        "id": 93,
        "name": "IDW",
        "type": "SMG",
        "damage": 26,
        "dodge": 85,
        "hit": 15,
        "attackSpeed": 75,
        "hp": 150,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Focus"
    },
    {
        "id": 94,
        "name": "Type 64",
        "type": "SMG",
        "damage": 27,
        "dodge": 65,
        "hit": 11,
        "attackSpeed": 93,
        "hp": 176,
        "reloadTime": null,
        "armor": null,
        "skill": "Flashbang"
    },
    {
        "id": 95,
        "name": "Hanyang Type 88",
        "type": "RF",
        "damage": 108,
        "dodge": 37,
        "hit": 60,
        "attackSpeed": 31,
        "hp": 102,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus N"
    },
    {
        "id": 96,
        "name": "Grizzly MkV",
        "type": "HG",
        "damage": 38,
        "dodge": 66,
        "hit": 51,
        "attackSpeed": 54,
        "hp": 86,
        "reloadTime": null,
        "armor": null,
        "skill": "Fire Command"
    },
    {
        "id": 97,
        "name": "M950A",
        "type": "HG",
        "damage": 30,
        "dodge": 68,
        "hit": 55,
        "attackSpeed": 72,
        "hp": 76,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Command"
    },
    {
        "id": 98,
        "name": "SPP-1",
        "type": "HG",
        "damage": 35,
        "dodge": 75,
        "hit": 61,
        "attackSpeed": 48,
        "hp": 76,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Suppression"
    },
    {
        "id": 99,
        "name": "Mk23",
        "type": "HG",
        "damage": 29,
        "dodge": 66,
        "hit": 53,
        "attackSpeed": 64,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Fire Command N"
    },
    {
        "id": 100,
        "name": "P7",
        "type": "HG",
        "damage": 32,
        "dodge": 83,
        "hit": 62,
        "attackSpeed": 62,
        "hp": 63,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Command"
    },
    {
        "id": 101,
        "name": "UMP9",
        "type": "SMG",
        "damage": 26,
        "dodge": 76,
        "hit": 14,
        "attackSpeed": 87,
        "hp": 176,
        "reloadTime": null,
        "armor": null,
        "skill": "Flashbang"
    },
    {
        "id": 103,
        "name": "UMP45",
        "type": "SMG",
        "damage": 28,
        "dodge": 74,
        "hit": 13,
        "attackSpeed": 82,
        "hp": 185,
        "reloadTime": null,
        "armor": null,
        "skill": "Smoke Grenade"
    },
    {
        "id": 104,
        "name": "G36C",
        "type": "SMG",
        "damage": 32,
        "dodge": 65,
        "hit": 12,
        "attackSpeed": 83,
        "hp": 203,
        "reloadTime": null,
        "armor": null,
        "skill": "Force Shield"
    },
    {
        "id": 105,
        "name": "OTs-12",
        "type": "AR",
        "damage": 42,
        "dodge": 54,
        "hit": 54,
        "attackSpeed": 72,
        "hp": 105,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus T"
    },
    {
        "id": 106,
        "name": "FAL",
        "type": "AR",
        "damage": 57,
        "dodge": 38,
        "hit": 40,
        "attackSpeed": 70,
        "hp": 132,
        "reloadTime": null,
        "armor": null,
        "skill": "High-Explosive Grenade"
    },
    {
        "id": 107,
        "name": "F2000",
        "type": "AR",
        "damage": 42,
        "dodge": 40,
        "hit": 44,
        "attackSpeed": 81,
        "hp": 105,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 108,
        "name": "CZ-805",
        "type": "AR",
        "damage": 43,
        "dodge": 41,
        "hit": 49,
        "attackSpeed": 75,
        "hp": 116,
        "reloadTime": null,
        "armor": null,
        "skill": "High-Explosive Grenade"
    },
    {
        "id": 109,
        "name": "MG5",
        "type": "MG",
        "damage": 85,
        "dodge": 29,
        "hit": 29,
        "attackSpeed": 120,
        "hp": 198,
        "reloadTime": 11,
        "armor": null,
        "skill": "Barrage End"
    },
    {
        "id": 110,
        "name": "FG42",
        "type": "MG",
        "damage": 87,
        "dodge": 33,
        "hit": 28,
        "attackSpeed": 121,
        "hp": 149,
        "reloadTime": 8,
        "armor": null,
        "skill": "Hunting Impulse"
    },
    {
        "id": 111,
        "name": "AAT-52",
        "type": "MG",
        "damage": 79,
        "dodge": 22,
        "hit": 24,
        "attackSpeed": 118,
        "hp": 182,
        "reloadTime": 10,
        "armor": null,
        "skill": "Firepower Focus N-MG"
    },
    {
        "id": 112,
        "name": "Negev",
        "type": "MG",
        "damage": 84,
        "dodge": 36,
        "hit": 35,
        "attackSpeed": 139,
        "hp": 174,
        "reloadTime": 9,
        "armor": null,
        "skill": "Frenzy"
    },
    {
        "id": 113,
        "name": "Serdyukov",
        "type": "HG",
        "damage": 33,
        "dodge": 68,
        "hit": 58,
        "attackSpeed": 58,
        "hp": 70,
        "reloadTime": null,
        "armor": null,
        "skill": "Fire Command"
    },
    {
        "id": 114,
        "name": "Welrod MkII",
        "type": "HG",
        "damage": 28,
        "dodge": 90,
        "hit": 71,
        "attackSpeed": 52,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Precision Suppression"
    },
    {
        "id": 115,
        "name": "Suomi",
        "type": "SMG",
        "damage": 28,
        "dodge": 56,
        "hit": 15,
        "attackSpeed": 93,
        "hp": 220,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Focus"
    },
    {
        "id": 116,
        "name": "Z-62",
        "type": "SMG",
        "damage": 27,
        "dodge": 77,
        "hit": 15,
        "attackSpeed": 77,
        "hp": 168,
        "reloadTime": null,
        "armor": null,
        "skill": "Incendiary Grenade"
    },
    {
        "id": 117,
        "name": "PSG-1",
        "type": "RF",
        "damage": 120,
        "dodge": 26,
        "hit": 73,
        "attackSpeed": 39,
        "hp": 93,
        "reloadTime": null,
        "armor": null,
        "skill": "Designated Shot"
    },
    {
        "id": 118,
        "name": "9A-91",
        "type": "AR",
        "damage": 42,
        "dodge": 50,
        "hit": 49,
        "attackSpeed": 78,
        "hp": 116,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus N"
    },
    {
        "id": 119,
        "name": "OTs-14",
        "type": "AR",
        "damage": 49,
        "dodge": 54,
        "hit": 54,
        "attackSpeed": 75,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus N"
    },
    {
        "id": 120,
        "name": "ARX-160",
        "type": "AR",
        "damage": 49,
        "dodge": 48,
        "hit": 48,
        "attackSpeed": 73,
        "hp": 99,
        "reloadTime": null,
        "armor": null,
        "skill": "Anti-personnel Grenade"
    },
    {
        "id": 121,
        "name": "Mk48",
        "type": "MG",
        "damage": 90,
        "dodge": 26,
        "hit": 24,
        "attackSpeed": 112,
        "hp": 174,
        "reloadTime": 10,
        "armor": null,
        "skill": "Hunting Impulse"
    },
    {
        "id": 122,
        "name": "G11",
        "type": "AR",
        "damage": 43,
        "dodge": 41,
        "hit": 44,
        "attackSpeed": 95,
        "hp": 121,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Eye"
    },
    {
        "id": 123,
        "name": "P99",
        "type": "HG",
        "damage": 31,
        "dodge": 87,
        "hit": 56,
        "attackSpeed": 61,
        "hp": 60,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Command"
    },
    {
        "id": 124,
        "name": "Super SASS",
        "type": "RF",
        "damage": 115,
        "dodge": 27,
        "hit": 65,
        "attackSpeed": 39,
        "hp": 88,
        "reloadTime": null,
        "armor": null,
        "skill": "Aimed Shot"
    },
    {
        "id": 125,
        "name": "MG4",
        "type": "MG",
        "damage": 84,
        "dodge": 34,
        "hit": 34,
        "attackSpeed": 139,
        "hp": 182,
        "reloadTime": 9,
        "armor": null,
        "skill": "Lock and Load"
    },
    {
        "id": 126,
        "name": "NZ75",
        "type": "HG",
        "damage": 73,
        "dodge": 74,
        "hit": 62,
        "attackSpeed": 63,
        "hp": 73,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Supression T"
    },
    {
        "id": 127,
        "name": "Type 79",
        "type": "SMG",
        "damage": 32,
        "dodge": 70,
        "hit": 12,
        "attackSpeed": 88,
        "hp": 194,
        "reloadTime": null,
        "armor": null,
        "skill": "Flashbang"
    },
    {
        "id": 128,
        "name": "M99",
        "type": "RF",
        "damage": 157,
        "dodge": 32,
        "hit": 81,
        "attackSpeed": 32,
        "hp": 88,
        "reloadTime": null,
        "armor": null,
        "skill": "Designated Shot"
    },
    {
        "id": 129,
        "name": "Type 95",
        "type": "AR",
        "damage": 55,
        "dodge": 46,
        "hit": 50,
        "attackSpeed": 71,
        "hp": 116,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus T"
    },
    {
        "id": 130,
        "name": "Type 97",
        "type": "AR",
        "damage": 54,
        "dodge": 46,
        "hit": 51,
        "attackSpeed": 72,
        "hp": 116,
        "reloadTime": null,
        "armor": null,
        "skill": "Assault Focus T"
    },
    {
        "id": 131,
        "name": "EVO 3",
        "type": "SMG",
        "damage": 23,
        "dodge": 68,
        "hit": 13,
        "attackSpeed": 93,
        "hp": 194,
        "reloadTime": null,
        "armor": null,
        "skill": "Hand Grenade"
    },
    {
        "id": 132,
        "name": "Type 59",
        "type": "HG",
        "damage": 28,
        "dodge": 96,
        "hit": 61,
        "attackSpeed": 61,
        "hp": 60,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Suppression N"
    },
    {
        "id": 133,
        "name": "Type 63",
        "type": "AR",
        "damage": 49,
        "dodge": 35,
        "hit": 35,
        "attackSpeed": 70,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": "Precision Focus"
    },
    {
        "id": 134,
        "name": "AR70",
        "type": "AR",
        "damage": 49,
        "dodge": 41,
        "hit": 43,
        "attackSpeed": 70,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": "Anti-Personnel Grenade"
    },
    {
        "id": 135,
        "name": "SR-3MP",
        "type": "SMG",
        "damage": 31,
        "dodge": 67,
        "hit": 12,
        "attackSpeed": 90,
        "hp": 185,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 136,
        "name": "PP-19",
        "type": "SMG",
        "damage": 26,
        "dodge": 74,
        "hit": 14,
        "attackSpeed": 91,
        "hp": 176,
        "reloadTime": null,
        "armor": null,
        "skill": "Hand Grenade"
    },
    {
        "id": 138,
        "name": "6P62",
        "type": "AR",
        "damage": 69,
        "dodge": 33,
        "hit": 37,
        "attackSpeed": 54,
        "hp": 121,
        "reloadTime": null,
        "armor": null,
        "skill": "Raid Focus"
    },
    {
        "id": 139,
        "name": "Bren Ten",
        "type": "HG",
        "damage": 31,
        "dodge": 63,
        "hit": 51,
        "attackSpeed": 58,
        "hp": 70,
        "reloadTime": null,
        "armor": null,
        "skill": "Fire Command"
    },
    {
        "id": 140,
        "name": "PSM",
        "type": "HG",
        "damage": 24,
        "dodge": 112,
        "hit": 67,
        "attackSpeed": 65,
        "hp": 57,
        "reloadTime": null,
        "armor": null,
        "skill": "Conceal Command"
    },
    {
        "id": 141,
        "name": "USP Compact",
        "type": "HG",
        "damage": 26,
        "dodge": 86,
        "hit": 60,
        "attackSpeed": 64,
        "hp": 66,
        "reloadTime": null,
        "armor": null,
        "skill": "Precision Command"
    },
    {
        "id": 142,
        "name": "Five-seveN",
        "type": "HG",
        "damage": 33,
        "dodge": 97,
        "hit": 57,
        "attackSpeed": 66,
        "hp": 63,
        "reloadTime": null,
        "armor": null,
        "skill": "Piercing Command"
    },
    {
        "id": 143,
        "name": "RO635",
        "type": "SMG",
        "damage": 29,
        "dodge": 71,
        "hit": 14,
        "attackSpeed": 97,
        "hp": 194,
        "reloadTime": null,
        "armor": null,
        "skill": "#"
    },
    {
        "id": 144,
        "name": "MT-9",
        "type": "SMG",
        "damage": 25,
        "dodge": 60,
        "hit": 13,
        "attackSpeed": 88,
        "hp": 203,
        "reloadTime": null,
        "armor": null,
        "skill": "Flashbang"
    },
    {
        "id": 145,
        "name": "OTs-44",
        "type": "RF",
        "damage": 159,
        "dodge": 32,
        "hit": 67,
        "attackSpeed": 32,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Locked Shot"
    },
    {
        "id": 146,
        "name": "G28",
        "type": "RF",
        "damage": 121,
        "dodge": 29,
        "hit": 80,
        "attackSpeed": 39,
        "hp": 88,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 147,
        "name": "SSG 69",
        "type": "RF",
        "damage": 130,
        "dodge": 39,
        "hit": 82,
        "attackSpeed": 30,
        "hp": 80,
        "reloadTime": null,
        "armor": null,
        "skill": "Firepower Focus"
    },
    {
        "id": 148,
        "name": "IWS-2000",
        "type": "RF",
        "damage": 164,
        "dodge": 29,
        "hit": 78,
        "attackSpeed": 32,
        "hp": 88,
        "reloadTime": null,
        "armor": null,
        "skill": ""
    },
    {
        "id": 149,
        "name": "AEK-999",
        "type": "MG",
        "damage": 91,
        "dodge": 28,
        "hit": 29,
        "attackSpeed": 120,
        "hp": 165,
        "reloadTime": 10,
        "armor": null,
        "skill": "Hunting Impulse N"
    },
    {
        "id": 150,
        "name": "Shipka",
        "type": "SMG",
        "damage": 26,
        "dodge": 79,
        "hit": 14,
        "attackSpeed": 95,
        "hp": 168,
        "reloadTime": null,
        "armor": null,
        "skill": "Cover Focus"
    },
    {
        "id": 151,
        "name": "M1887",
        "type": "SG",
        "damage": 39,
        "dodge": 12,
        "hit": 12,
        "attackSpeed": 22,
        "hp": 275,
        "reloadTime": null,
        "armor": 22,
        "skill": "Terminating shot"
    },
    {
        "id": 152,
        "name": "M1897",
        "type": "SG",
        "damage": 37,
        "dodge": 11,
        "hit": 11,
        "attackSpeed": 26,
        "hp": 253,
        "reloadTime": 4,
        "armor": 21,
        "skill": "Burst Impact"
    },
    {
        "id": 153,
        "name": "M37",
        "type": "SG",
        "damage": 33,
        "dodge": 12,
        "hit": 12,
        "attackSpeed": 26,
        "hp": 253,
        "reloadTime": 4,
        "armor": 24,
        "skill": "Burst Impact"
    },
    {
        "id": 154,
        "name": "M500",
        "type": "SG",
        "damage": 31,
        "dodge": 10,
        "hit": 11,
        "attackSpeed": 29,
        "hp": 264,
        "reloadTime": 4,
        "armor": 23,
        "skill": "Ironside Concentration"
    },
    {
        "id": 155,
        "name": "M590",
        "type": "SG",
        "damage": 32,
        "dodge": 10,
        "hit": 11,
        "attackSpeed": 31,
        "hp": 264,
        "reloadTime": 4,
        "armor": 24,
        "skill": "Ironside Concentration"
    },
    {
        "id": 156,
        "name": "Super-Shorty",
        "type": "SG",
        "damage": 30,
        "dodge": 19,
        "hit": 14,
        "attackSpeed": 30,
        "hp": 242,
        "reloadTime": 3,
        "armor": 20,
        "skill": "Survival Instinct"
    },
    {
        "id": 157,
        "name": "KSG",
        "type": "SG",
        "damage": 29,
        "dodge": 12,
        "hit": 13,
        "attackSpeed": 30,
        "hp": 253,
        "reloadTime": 5,
        "armor": 26,
        "skill": "Survival Instinct"
    },
    {
        "id": 158,
        "name": "KS-23",
        "type": "SG",
        "damage": 40,
        "dodge": 10,
        "hit": 9,
        "attackSpeed": 25,
        "hp": 275,
        "reloadTime": 3,
        "armor": 23,
        "skill": "Firepower Focus SG"
    },
    {
        "id": 159,
        "name": "RMB-93",
        "type": "SG",
        "damage": 30,
        "dodge": 13,
        "hit": 11,
        "attackSpeed": 28,
        "hp": 242,
        "reloadTime": 4,
        "armor": 24,
        "skill": "Burst Impact"
    },
    {
        "id": 160,
        "name": "Saiga-12",
        "type": "SG",
        "damage": 31,
        "dodge": 11,
        "hit": 12,
        "attackSpeed": 35,
        "hp": 264,
        "reloadTime": 5,
        "armor": 23,
        "skill": "Big Antelope's Horn"
    },
    {
        "id": 161,
        "name": "Type 97 Shotgun",
        "type": "SG",
        "damage": 33,
        "dodge": 13,
        "hit": 12,
        "attackSpeed": 27,
        "hp": 264,
        "reloadTime": null,
        "armor": 22,
        "skill": "Firepower Focus SG"
    },
    {
        "id": 162,
        "name": "SPAS-12",
        "type": "SG",
        "damage": 35,
        "dodge": 9,
        "hit": 11,
        "attackSpeed": 32,
        "hp": 275,
        "reloadTime": 4,
        "armor": 21,
        "skill": "Firepower Focus SG"
    },
    {
        "id": 166,
        "name": "CZ75",
        "type": "HG",
        "damage": 36,
        "dodge": 74,
        "hit": 62,
        "attackSpeed": 66,
        "hp": 66,
        "reloadTime": null,
        "armor": null,
        "skill": ""
    },
    {
        "id": 167,
        "name": "HK45",
        "type": "HG",
        "damage": 34,
        "dodge": 80,
        "hit": 58,
        "attackSpeed": 55,
        "hp": 66,
        "reloadTime": null,
        "armor": null,
        "skill": ""
    },
    {
        "id": 168,
        "name": "Spitfire",
        "type": "HG",
        "damage": 33,
        "dodge": 71,
        "hit": 60,
        "attackSpeed": 59,
        "hp": 70,
        "reloadTime": null,
        "armor": null,
        "skill": ""
    },
    {
        "id": 170,
        "name": "ASh-12.7",
        "type": "AR",
        "damage": 67,
        "dodge": 36,
        "hit": 41,
        "attackSpeed": 59,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": ""
    },
    {
        "id": 171,
        "name": "Ribeyrolles",
        "type": "AR",
        "damage": 64,
        "dodge": 40,
        "hit": 44,
        "attackSpeed": 63,
        "hp": 110,
        "reloadTime": null,
        "armor": null,
        "skill": ""
    },
    {
        "id": 172,
        "name": "RFB",
        "type": "AR",
        "damage": 69,
        "dodge": 49,
        "hit": 68,
        "attackSpeed": 54,
        "hp": 105,
        "reloadTime": null,
        "armor": null,
        "skill": "Ammo Supremacy"
    },
    {
        "id": 173,
        "name": "PKP",
        "type": "MG",
        "damage": 95,
        "dodge": 29,
        "hit": 31,
        "attackSpeed": 127,
        "hp": 165,
        "reloadTime": 10,
        "armor": null,
        "skill": "Ultimatum"
    }
];
